server:
  port: 8081
spring:
  redis:
    host: 42.192.160.109
    password: leiRedis..
    database: 15
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.160.109:3306/learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: leimysql..

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


