server:
  port: 8081
spring:
  cache:
    # ehcache配置
    ehcache:
      config: classpath:/ehcache.xml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: leimysql..

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


