spring:
  datasource:
    url: jdbc:mysql://10.50.125.200:3306/demotest?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
