spring:
    #我这里仅写了ip 其余端口账号密码由于是演示 采用默认即可，不必要写
  rabbitmq:
    host: 10.50.40.116
    port: 5673
    username: admin
    password: admin
    # 开启消息确认机制 confirm 异步
#    publisher-confirm-type: correlated
#    listener:
#      direct:
#        # 消息开启手动确认 （ confirm 测试时开启）
#        acknowledge-mode: manual
#    publisher-returns: true
#  main:
#    allow-bean-definition-overriding: true