spring:
  redis:
    host: 10.50.50.116
    port: 6379
    database: 0
    password: leiRedis..
    # 使用lettuce连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1ms
        max-wait: -1
