spring:
  datasource:
    url: jdbc:mysql://10.50.125.200:3306/demotest?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 1
      maximum-pool-size: 1
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


minio:
  endpoint: http://10.50.125.197:9000
  access-key: admin
  secret-key: 123456789
  bucket: eamp-dev
logging:
  level:
    org.springframework.jdbc: debug
    org.springframework.transaction: trace
