spring:
    #我这里仅写了ip 其余端口账号密码由于是演示 采用默认即可，不必要写
  rabbitmq:
    host: 10.50.40.116
    port: 5673
    username: admin
    password: admin
    listener:
      direct:
        # 消息开启手动确认
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 3000

