timely:
  # 是否开启
  switch: true
  # 偏移量文件
  offset-file-name: /opt/lei/offsets.dat
  # 是否启东时清除偏移量文件
  offset-file-clean: true
  # 偏移量提交时间 单位ms
  offset-time: 1
  # 读取历史记录文件
  history-file-name: /opt/lei/dbhistory.dat
  # 读取的数据库信息
  offline:
    ip: 192.168.73.233
    port: 1433
    username: xxx
    password: Hx28!cvniud93c
    # 保证每个数据库读取的 instance-name  logic-name 不能相同
    # 实例名
    instance-name: sc-mssql-connector
    # 逻辑名
    logic-name: sc-mssql-customer
    # 读取的表
    include-table: dbo.vehicle
    # 读取的库
    include-db: gps
