spring:
  kafka:
    bootstrap-servers: 10.50.125.194:9092
    producer:
      properties:
        linger.ms: 100
    consumer:
      max-poll-records: 20
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
      type: batch


kafka:
  calcTopic: pos-test
  groupId: calc-test
  calcSleep: 200
